#!/bin/bash

if [[ "$1" == "loft" ]]; then

  if [[ "$2" == "up" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=32&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "down" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=33&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "info" ]]; then
    INFO=$(curl -sS "http://192.168.1.200/zonedata/controller_1_zone_5.xml" | sed 's/<[^>]*>//g' | xargs)

    META=$(curl -sS "http://192.168.1.200/metadata/metadata_source_1.xml" | grep "CDATA" | grep -v -- "-----" | sed 's/.*\[\([^]]*\)\].*/\1/g')

    INFO_VALUES=($INFO)
    echo

    case "${INFO_VALUES[2-1]}" in
      5 )
      echo "$(tput setaf 6)$(tput bold)Source:  $(tput setaf 7)Computer$(tput sgr0)"
        ;;

        0 )
        echo "$(tput setaf 6)$(tput bold)Source:  $(tput setaf 7)Sirius XM$(tput sgr0)"
          ;;

          * )
          echo "$(tput setaf 6)$(tput bold)Source:  $(tput setaf 7)Other$(tput sgr0)"
            ;;
    esac

    case "${INFO_VALUES[3-1]}" in
      0 )
      echo "$(tput setaf 6)$(tput bold)Volume:  $(tput setaf 7)Muted$(tput sgr0)"
        ;;

        * )
        echo "$(tput setaf 6)$(tput bold)Volume:  $(tput setaf 7)${INFO_VALUES[3-1]}$(tput sgr0)"
          ;;
    esac


    if [[ "${INFO_VALUES[2-1]}" == 0 ]]; then
      echo $(tput setaf 6)$(tput bold)Station: $(tput setaf 7)$(echo "$META" | tail -1 )$(tput sgr0)
    fi

    if [[ "${INFO_VALUES[2-1]}" == 0 ]]; then
      echo $(tput setaf 6)$(tput bold)"Artist:  "$(tput setaf 7)$(echo "$META" | head -1)$(tput sgr0)
    fi

    if [[ "${INFO_VALUES[2-1]}" == 0 ]]; then
      echo $(tput setaf 6)$(tput bold)"Song:    "$(tput setaf 7)$(echo "$META" | sed "2!d")$(tput sgr0)
    fi


echo

  elif [[ "$2" == "off" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=1&zoneid=5&value=0&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "on" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=1&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "xm" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=7&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "comp" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=7&zoneid=5&value=6&controllerid=1&controllertype=1" > /dev/null


  elif [[ "$2" == "next" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=23&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null

  elif [[ "$2" == "back" ]]; then
    curl -sS "http://192.168.1.200/cgi-bin/control?action=24&zoneid=5&value=1&controllerid=1&controllertype=1" > /dev/null


else
  echo
  echo "$(tput setaf 1)$(tput bold)Invalid command $2!$(tput sgr0)"
  echo
  exit

fi

fi
